'use client';

import React, { createContext, useContext, useState } from 'react';

// Define translations for each language
const translations = {
  en: {
    welcome: "Welcome",
    haveAGreatDay: "Have a great day!",
    taskManagement: "Task Management",
    addTask: "Add Task",
    taskProgress: "Task Progress",
    completed: "Completed",
    filterByPriority: "Filter by Priority",
    all: "All",
    high: "High",
    medium: "Medium",
    low: "Low",
    "to-do": "To Do",
    "in-progress": "In Progress",
    done: "Done",
    edit: "Edit",
    delete: "Delete",
    addNewTask: "Add New Task",
    taskContent: "Task Content",
    priority: "Priority",
    selectPriority: "Select Priority",
    saveChanges: "Save Changes",
    profile: "Profile",
    taskManager: "Task Manager",
    noEvents: "No events scheduled for this day.",
    eventDetails: "Event Details",
    familyCalendarTitle: "Family Calendar",
    childManagement: "Child Management",
    addChild: "Add Child",
    name: "Name",
    username: "Username",
    password: "Password",
    children: "Children",
    assignTask: "Assign Task",
    taskTitle: "Task Title",
    description: "Description",
    dueDate: "Due Date",
    selectChild: "Select Child",
    selectTask: "Select Task",
    assign: "Assign",
    high: "High",
    medium: "Medium",
    low: "Low",
    all: "All",
    progress: "Progress",
    addEvent:"Add Event"
  },
  es: {
    welcome: "Bienvenido",
    addEvent: "Agregar evento",
    haveAGreatDay: "¡Que tengas un buen día!",
    taskManagement: "Gestión de Tareas",
    addTask: "Añadir Tarea",
    taskProgress: "Progreso de Tareas",
    completed: "Completado",
    filterByPriority: "Filtrar por Prioridad",
    all: "Todos",
    high: "Alta",
    medium: "Media",
    low: "Baja",
    "to-do": "Por Hacer",
    "in-progress": "En Progreso",
    done: "Hecho",
    edit: "Editar",
    delete: "Eliminar",
    addNewTask: "Añadir Nueva Tarea",
    taskContent: "Contenido de la Tarea",
    priority: "Prioridad",
    selectPriority: "Seleccionar Prioridad",
    saveChanges: "Guardar Cambios",
    profile: "Perfil",
    taskManager: "Gestor de Tareas",
    noEvents: "No hay eventos programados para este día.",
    eventDetails: "Detalles del Evento",
    familyCalendarTitle: "Calendario Familiar",
    childManagement: "Gestión de Niños",
    addChild: "Añadir Niño",
    name: "Nombre",
    username: "Nombre de Usuario",
    password: "Contraseña",
    children: "Niños",
    assignTask: "Asignar Tarea",
    taskTitle: "Título de la Tarea",
    description: "Descripción",
    dueDate: "Fecha de Vencimiento",
    selectChild: "Seleccionar Niño",
    selectTask: "Seleccionar Tarea",
    assign: "Asignar",
    high: "Alta",
    medium: "Media",
    low: "Baja",
    all: "Todos",
    progress: "Progreso",
  },
  fr: {
    welcome: "Bienvenue",
    addEvent: "Ajouter un événement",

    haveAGreatDay: "Bonne journée!",
    taskManagement: "Gestion des Tâches",
    addTask: "Ajouter une Tâche",
    taskProgress: "Progrès des Tâches",
    completed: "Terminé",
    filterByPriority: "Filtrer par Priorité",
    all: "Tous",
    high: "Élevée",
    medium: "Moyenne",
    low: "Faible",
    "to-do": "À Faire",
    "in-progress": "En Cours",
    done: "Fait",
    edit: "Modifier",
    delete: "Supprimer",
    addNewTask: "Ajouter une Nouvelle Tâche",
    taskContent: "Contenu de la Tâche",
    priority: "Priorité",
    selectPriority: "Sélectionner la Priorité",
    saveChanges: "Sauvegarder les Modifications",
    profile: "Profil",
    taskManager: "Gestionnaire de Tâches",
    noEvents: "Aucun événement prévu pour ce jour.",
    eventDetails: "Détails de l'Événement",
    familyCalendarTitle: "Calendrier Familial",
    childManagement: "Gestion des Enfants",
    addChild: "Ajouter un Enfant",
    name: "Nom",
    username: "Nom d'Utilisateur",
    password: "Mot de Passe",
    children: "Enfants",
    assignTask: "Assigner une Tâche",
    taskTitle: "Titre de la Tâche",
    description: "Description",
    dueDate: "Date d'Échéance",
    selectChild: "Sélectionner un Enfant",
    selectTask: "Sélectionner une Tâche",
    assign: "Assigner",
    high: "Élevée",
    medium: "Moyenne",
    low: "Faible",
    all: "Tous",
    progress: "Progrès",
  },
  de: {
    welcome: "Willkommen",
    addEvent: "Ereignis hinzufügen",

    haveAGreatDay: "Einen schönen Tag noch!",
    taskManagement: "Aufgabenverwaltung",
    addTask: "Aufgabe Hinzufügen",
    taskProgress: "Aufgabenfortschritt",
    completed: "Abgeschlossen",
    filterByPriority: "Nach Priorität filtern",
    all: "Alle",
    high: "Hoch",
    medium: "Mittel",
    low: "Niedrig",
    "to-do": "Zu Erledigen",
    "in-progress": "In Bearbeitung",
    done: "Erledigt",
    edit: "Bearbeiten",
    delete: "Löschen",
    addNewTask: "Neue Aufgabe hinzufügen",
    taskContent: "Aufgabeninhalt",
    priority: "Priorität",
    selectPriority: "Priorität auswählen",
    saveChanges: "Änderungen speichern",
    profile: "Profil",
    taskManager: "Aufgabenmanager",
    noEvents: "Keine Ereignisse für diesen Tag geplant.",
    eventDetails: "Ereignisdetails",
    familyCalendarTitle: "Familienkalender",
    childManagement: "Kinderverwaltung",
    addChild: "Kind Hinzufügen",
    name: "Name",
    username: "Benutzername",
    password: "Passwort",
    children: "Kinder",
    assignTask: "Aufgabe Zuweisen",
    taskTitle: "Aufgabentitel",
    description: "Beschreibung",
    dueDate: "Fälligkeitsdatum",
    selectChild: "Kind Auswählen",
    selectTask: "Aufgabe Auswählen",
    assign: "Zuweisen",
    high: "Hoch",
    medium: "Mittel",
    low: "Niedrig",
    all: "Alle",
    progress: "Fortschritt",
  },
  ru: {
    welcome: "Добро пожаловать",
    haveAGreatDay: "Хорошего дня!",
    taskManagement: "Управление задачами",
    addTask: "Добавить задачу",
    taskProgress: "Прогресс задач",
    completed: "Завершено",
    filterByPriority: "Фильтровать по приоритету",
    all: "Все",
    high: "Высокий",
    medium: "Средний",
    low: "Низкий",
    addEvent: "Добавить событие",

    "to-do": "К выполнению",
    "in-progress": "В процессе",
    done: "Сделано",
    edit: "Редактировать",
    delete: "Удалить",
    addNewTask: "Добавить новую задачу",
    taskContent: "Содержание задачи",
    priority: "Приоритет",
    selectPriority: "Выбрать приоритет",
    saveChanges: "Сохранить изменения",
    profile: "Профиль",
    taskManager: "Менеджер задач",
    noEvents: "На этот день нет запланированных событий.",
    eventDetails: "Детали события",
    familyCalendarTitle: "Семейный календарь",
    childManagement: "Управление Детьми",
    addChild: "Добавить Ребенка",
    name: "Имя",
    username: "Имя Пользователя",
    password: "Пароль",
    children: "Дети",
    assignTask: "Назначить Задачу",
    taskTitle: "Название Задачи",
    description: "Описание",
    dueDate: "Срок Выполнения",
    selectChild: "Выбрать Ребенка",
    selectTask: "Выбрать Задачу",
    assign: "Назначить",
    high: "Высокий",
    medium: "Средний",
    low: "Низкий",
    all: "Все",
    progress: "Прогресс",
  },
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const value = {
    language,
    setLanguage,
    t: translations[language], // Current translations based on the selected language
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};