'use client';

import React, { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    welcome: "Welcome",
    edit: "Edit",
    delete: "Delete",
    priorityHigh: "High",
    priorityMedium: "Medium",
    priorityLow: "Low",
    haveAGreatDay: "Have a great day!",
    weeklyTaskOverview: "Weekly Task Overview",
    todaysProgress: "Today's Progress",
    tasksCompleted: "Tasks Completed",
    studyTime: "Study Time",
    exercise: "Exercise",
    upcomingEvents: "Upcoming Events",
    quickActions: "Quick Actions",
    addTask: "Add Task",
    scheduleEvent: "Schedule Event",
    shoppingList: "Shopping List",
    rewards: "Rewards",
    calendar: "Calendar",
    tasks: "Tasks",
    shopping: "Shopping",
    budget: "Budget",
    mealPlanner: "Meal Planner",
    finance: "Finance",
    // Calendar-specific translations
    familyCalendarTitle: "Family Calendar",
    addEvent: "Add Event",
    noEvents: "No events scheduled for this day.",
    newEvent: "New Event",
    eventDetails: "Event Details",
    ///...more 
    takePhoto:"Take Photo",
    retakePhoto:"Retake Photo",
    welcome: "Welcome",
    usePhoto:"User Photo",
    haveAGreatDay: "Have a great day!",
    personalInfo: "Personal Information",
    childrenInfo: "Children Information",
    additionalDetails: "Additional Details",
    fullName: "Full Name",
    username: "Username",
    email: "Email",
    phone: "Phone Number",
    address: "Address",
    street: "Street",
    city: "City",
    welcome: "Welcome",
    haveAGreatDay: "Have a great day!",
    taskManagement: "Task Management",
    addTask: "Add Task",
    taskProgress: "Task Progress",
    completed: "Completed",
    filterByPriority: "Filter by Priority",
    all: "All",
    high: "High",
    medium: "Medium",
    low: "Low",
    "to-do": "To Do",
    "in-progress": "In Progress",
    done: "Done",
    edit: "Edit",
    delete: "Delete",
    addNewTask: "Add New Task",
    taskContent: "Task Content",
    priority: "Priority",
    selectPriority: "Select Priority",
    saveChanges: "Save Changes",
    profile: "Profile",
    taskManager: "Task Manager",
    noEvents: "No events scheduled for this day.",
    eventDetails: "Event Details",
    familyCalendarTitle: "Family Calendar",
    childManagement: "Child Management",
    addChild: "Add Child",
    name: "Name",
    username: "Username",
    password: "Password",
    children: "Children",
    assignTask: "Assign Task",
    taskTitle: "Task Title",
    description: "Description",
    dueDate: "Due Date",
    selectChild: "Select Child",
    selectTask: "Select Task",
    assign: "Assign",
    high: "High",
    medium: "Medium",
    low: "Low",
    all: "All",
    progress: "Progress",
    addEvent:"Add Event",

    state: "State",
    zipCode: "Zip Code",
    country: "Country",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    male: "Male",
    female: "Female",
    nonBinary: "Non-Binary",
    preferNotToSay: "Prefer Not to Say",
    nationality: "Nationality",
    maritalStatus: "Marital Status",
    single: "Single",
    married: "Married",
    divorced: "Divorced",
    widowed: "Widowed",
    occupation: "Occupation",
    profilePicture: "Profile Picture",
    addChild: "Add Child",
    removeChild: "Remove Child",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    skipChildrenSection: "Skip Children Section",
    formSubmitted: "Form submitted successfully!",
    invalidEmail: "Invalid email address",
    requiredField: "This field is required",
    invalidPhone: "Invalid phone number",
    additionalDetails: "Additional Details",
    enableNotifications: "Enable Notifications",
    currentPassword: "Current Password",
    newPassword: "New Password",
    confirmPassword: "Confirm Password",
    emergencyContactName: "Emergency Contact Name",
    emergencyContactPhone: "Emergency Contact Phone",
    socialMediaLinks: "Social Media Links",
    facebook: "Facebook",
    childInformation: "Child Information {{number}}",
    addChild: "Add Child",
    childInformation: "Child Information {{number}}",
    removeChild: "Remove Child",
    name: "Name",
    dateOfBirth: "Date of Birth",
    gender: "Gender",
    male: "Male",
    female: "Female",
    nonBinary: "Non-Binary",
    preferNotToSay: "Prefer Not to Say",
    gradeClass: "Grade/Class",
    guardianRole: "Guardian Role",
    father: "Father",
    mother: "Mother",
    other: "Other",
    childImage: "Child's Image",
    uploadImage: "Upload Image",
    additionalNotes: "Additional Notes",
    skipChildrenSection: "Skip Children Section",
    requiredField: "This field is required",
    selectGuardianRole: "Select Guardian Role",
    invalidPhone: "Invalid phone number",
    twitter: "Twitter",
    linkedin: "LinkedIn",
    instagram: "Instagram",
    invalidPhone: "Invalid phone number",
    requiredField: "This field is required",
  },
  es: {
    welcome: "Bienvenido",
    haveAGreatDay: "¡Que tengas un buen día!",
    weeklyTaskOverview: "Resumen semanal de tareas",
    todaysProgress: "Progreso de hoy",
    tasksCompleted: "Tareas completadas",
    studyTime: "Tiempo de estudio",
    exercise: "Ejercicio",
    upcomingEvents: "Próximos eventos",
    quickActions: "Acciones rápidas",
    addTask: "Agregar tarea",
    scheduleEvent: "Programar evento",
    shoppingList: "Lista de compras",
    rewards: "Recompensas",
    calendar: "Calendario",
    tasks: "Tareas",
    shopping: "Compras",
    budget: "Presupuesto",
    mealPlanner: "Planificador de comidas",
    finance: "Finanzas",
    familyCalendarTitle: "Calendario Familiar",
    addEvent: "Añadir Evento",
    noEvents: "No hay eventos programados para este día.",
    newEvent: "Nuevo Evento",
    eventDetails: "Detalles del Evento",
  },
  fr: {
    welcome: "Bienvenue",
    haveAGreatDay: "Bonne journée!",
    weeklyTaskOverview: "Aperçu des tâches hebdomadaires",
    todaysProgress: "Progrès d'aujourd'hui",
    tasksCompleted: "Tâches terminées",
    studyTime: "Temps d'étude",
    exercise: "Exercice",
    upcomingEvents: "Événements à venir",
    quickActions: "Actions rapides",
    addTask: "Ajouter une tâche",
    scheduleEvent: "Planifier un événement",
    shoppingList: "Liste de courses",
    rewards: "Récompenses",
    calendar: "Calendrier",
    tasks: "Tâches",
    shopping: "Courses",
    budget: "Budget",
    mealPlanner: "Planificateur de repas",
    finance: "Finances",
    familyCalendarTitle: "Calendrier Familial",
    addEvent: "Ajouter un Événement",
    noEvents: "Aucun événement prévu pour ce jour.",
    newEvent: "Nouvel Événement",
    eventDetails: "Détails de l'Événement",
  },
  de: {
    welcome: "Willkommen",
    haveAGreatDay: "Einen schönen Tag noch!",
    weeklyTaskOverview: "Wöchentliche Aufgabenübersicht",
    todaysProgress: "Heutiger Fortschritt",
    tasksCompleted: "Erledigte Aufgaben",
    studyTime: "Lernzeit",
    exercise: "Übung",
    upcomingEvents: "Kommende Veranstaltungen",
    quickActions: "Schnellaktionen",
    addTask: "Aufgabe hinzufügen",
    scheduleEvent: "Ereignis planen",
    shoppingList: "Einkaufsliste",
    rewards: "Belohnungen",
    calendar: "Kalender",
    tasks: "Aufgaben",
    shopping: "Einkaufen",
    budget: "Budget",
    mealPlanner: "Mahlzeitenplaner",
    finance: "Finanzen",
    familyCalendarTitle: "Familienkalender",
    addEvent: "Ereignis hinzufügen",
    noEvents: "Keine Ereignisse für diesen Tag geplant.",
    newEvent: "Neues Ereignis",
    eventDetails: "Ereignisdetails",
  },
  ru: {
    welcome: "Добро пожаловать",
    haveAGreatDay: "Хорошего дня!",
    weeklyTaskOverview: "Еженедельный обзор задач",
    todaysProgress: "Прогресс на сегодня",
    tasksCompleted: "Завершенные задачи",
    studyTime: "Время на учебу",
    exercise: "Упражнения",
    upcomingEvents: "Предстоящие события",
    quickActions: "Быстрые действия",
    addTask: "Добавить задачу",
    scheduleEvent: "Запланировать событие",
    shoppingList: "Список покупок",
    rewards: "Награды",
    calendar: "Календарь",
    tasks: "Задачи",
    shopping: "Покупки",
    budget: "Бюджет",
    mealPlanner: "Планировщик питания",
    finance: "Финансы",
    familyCalendarTitle: "Семейный календарь",
    addEvent: "Добавить событие",
    noEvents: "На этот день нет запланированных событий.",
    newEvent: "Новое событие",
    eventDetails: "Детали события",
  },
};

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('en');

  const value = {
    language,
    setLanguage,
    t: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};